# Generated by Django 2.2.2 on 2019-06-11 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hell_log.Account')),
            ],
        ),
        migrations.CreateModel(
            name='HellRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('HellType', models.CharField(max_length=15)),
                ('Runs', models.IntegerField(default=1)),
                ('HellOrb', models.IntegerField(default=0)),
                ('StoneBox', models.IntegerField(default=0)),
                ('EpicSoul', models.IntegerField(default=0)),
                ('EpicDrops', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hell_log.Character')),
            ],
        ),
    ]
