# Generated by Django 2.2.2 on 2019-06-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hellruns',
            name='Date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='hellruns',
            name='HellType',
            field=models.CharField(choices=[('hh', 'Harlem Hell'), ('SR', 'Sky Rift'), ('CR', 'Celestial Rift')], default='hh', max_length=2),
        ),
    ]
