# Generated by Django 2.2.2 on 2019-06-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell_log', '0002_auto_20190612_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hellruns',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
