# Generated by Django 2.2.2 on 2019-06-12 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell_log', '0003_auto_20190612_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hellruns',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
