# Generated by Django 2.2.2 on 2019-07-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell_log', '0004_auto_20190612_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='hellruns',
            name='AntiMatterParticle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hellruns',
            name='SkyFrags',
            field=models.IntegerField(default=0),
        ),
    ]
