# Generated by Django 2.2.2 on 2019-07-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hell_log', '0005_auto_20190711_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hellruns',
            old_name='AntiMatterParticle',
            new_name='AntimatterParticle',
        ),
    ]
