# Generated by Django 2.2.2 on 2019-07-18 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hell_log', '0006_auto_20190711_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
