# Generated by Django 2.2.2 on 2019-07-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hell_log', '0007_auto_20190718_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='subclass',
            new_name='Subclass',
        ),
    ]
