# Generated by Django 2.2.2 on 2020-04-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hell_log', '0008_auto_20190718_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hellruns',
            name='AntimatterParticle',
        ),
        migrations.RemoveField(
            model_name='hellruns',
            name='HellOrb',
        ),
        migrations.RemoveField(
            model_name='hellruns',
            name='SkyFrags',
        ),
        migrations.AlterField(
            model_name='hellruns',
            name='HellType',
            field=models.CharField(choices=[('GW', 'Guide of Wisdom')], default='GW', max_length=2),
        ),
    ]
